DROP TABLE CART;
DROP TABLE ORDERDETAIL;
DROP TABLE ORDERS;
DROP TABLE PRODUCT;
DROP TABLE MEMBER;

CREATE TABLE MEMBER (
    MNO VARCHAR2(10) PRIMARY KEY,
    MNAME VARCHAR2(50),
    MADDR VARCHAR2(255),
    MTEL VARCHAR2(30),
    MMAIL VARCHAR2(40) );
    
CREATE TABLE PRODUCT (
    PCODE VARCHAR2(5) PRIMARY KEY,
    PNAME VARCHAR2(50),
    PPRICE NUMBER(9),
    PSTOCK NUMBER(3) );
    
CREATE TABLE CART (
    CNO NUMBER(4) PRIMARY KEY,
    MNO VARCHAR2(10) REFERENCES MEMBER(MNO),
    PCODE VARCHAR2(5) REFERENCES PRODUCT(PCODE),
    QTY NUMBER(3),
    COST NUMBER(9) );
    
CREATE TABLE ORDERS (
    ONO   NUMBER PRIMARY KEY,
	MNO   VARCHAR2(10) REFERENCES MEMBER(MNO),
	OADDR VARCHAR2(255),
	OTEL  VARCHAR2(30) ,
	ODATE DATE );

CREATE TABLE ORDERDETAIL (
    ODNO    NUMBER(4) PRIMARY KEY,
    ONO     NUMBER REFERENCES ORDERS(ONO),
    PCODE   VARCHAR2(5) REFERENCES PRODUCT(PCODE),
    QTY     NUMBER(3),
    COST    NUMBER(9) );
    
SELECT * FROM MEMBER;
SELECT * FROM PRODUCT;
SELECT * FROM CART;
SELECT * FROM ORDERS;
SELECT * FROM ORDERDETAIL;